Arsh_job_packets/urls.py
from django.conf.urls import url, include
from django.contrib import admin
# from . import views

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from job_packet.views import profile
from django.contrib.auth import views as auth_views
from django.conf.urls import (
handler400, handler403, handler404, handler500
)
import django.views.defaults
# handler400 = 'job_packet.views.handler404'
# handler403 = 'my_app.views.permission_denied'
handler404 = ' job_packet.views.handler404'
handler500 = 'job_packet.views.handler500'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('job_packet.urls')),
    # url(r'^404/$',django.views.defaults.page_not_found,),
    # url(r'^500/$',django.views.defaults.server_error,),
    # url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/login/'}, name='logout'),
]

job_packet/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.show_packets, name='show_packet'),
    url(r'^register/$', views.add_client, name='add_client'),
    url(r'^(?P<pk>\d+)/$', views.packet_detail, name='packet_detail'),
    url(r'^profile/$',views.profile,  name='profile'),
    url(r'^edit_profile/$',views.edit_profile,  name='edit_profile'),
    url(r'^login/$', views.login_user,  name='login'),


]

job_packet/models.py
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import User
from django.db import models
# Create your models here.
from khayyam import *
from django.utils import timezone
from django.contrib.auth.models import AbstractUser
from job_packet.func import create_time
from django.db import models


class Packet(models.Model):
    pub_date = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.pub_date)


class Job(models.Model):
    heading=models.CharField(max_length=100)
    start_date =models.TimeField(default=timezone.now().strftime('%H:%M'))
    finish_date =models.TimeField(null=True,default=None)
    # lenght_date =models.CharField(null=True,default=None)
    packet = models.ForeignKey(Packet, on_delete=models.CASCADE)
    @property
    def diff(self):
        if self.finish_date==None:
            return None
        t_a = str(self.start_date)
        # print('\n\n\n\n',t_a)
        t_b = str(self.finish_date)

        s = t_a.split(":")
        # g=s[1].split(":")
        s1 = int(s[1]) * 60 + int(s[0])
        s2 = t_b.split(":")
        # g2= s2[1].split(":")
        s3 = int(s2[1]) * 60 + int(s2[0])

        minutesDiff = s1 - s3

        print(minutesDiff)

        h = minutesDiff // 60
        m = minutesDiff - (h * 60)
        s = ""
        if h > 0:
            s = s + str(h) + " ساعت "
        if m > 0:
            s = s + str(m) + " دقیقه "
        if s == "":
            return "0 دقیقه"
        else:
            # print(s)
            return s

    def __str__(self):
        return str(self.heading)


class Client(models.Model):
    name = models.CharField(max_length=128)
    surname = models.CharField(max_length=128)
    phone = models.CharField(max_length=11,help_text='09129999999')
    email= models.EmailField(max_length=128, unique= True)
    picture = models.ImageField(upload_to='static/images/profile_pics', blank=True, default='static/images/profile_pics/new_logo.png')

    def __str__(self):
        return self.name

job_packet/forms.py
from django import forms
from jalali_date.fields import JalaliDateField, SplitJalaliDateTimeField
from jalali_date.widgets import AdminJalaliDateWidget, AdminSplitJalaliDateTime
from job_packet.models import Client
from django.forms import CharField, Form, PasswordInput

# class TestForm(forms.ModelForm):
#     class Meta:
#         model = TestModel
#         fields = ('name', 'date', 'date_time')
#
#     def __init__(self, *args, **kwargs):
#         super(TestForm, self).__init__(*args, **kwargs)
#         self.fields['date'] = JalaliDateField(label=_('date'),
#             widget=AdminJalaliDateWidget # optional, for user default datepicker
#         )
#         # you can added a "class" to this field for user your datepicker!
#         # self.fields['date'].widget.attrs.update({'class': 'jalali_date-date'})
#
#         self.fields['date_time'] = SplitJalaliDateTimeField(label=_('date time'),
#             widget=AdminSplitJalaliDateTime # required, for decompress DatetimeField to JalaliDateField and JalaliTimeField
#         )

class ClientForm(forms.Form):
    # email= forms.CharField()
    # # username = forms.CharField(max_length=128)
    # password = forms.CharField(widget=PasswordInput())
    # name = forms.CharField()
    # surname = forms.CharField()
    # phone = forms.IntegerField()
    # # address = forms.CharField(max_length=128, help_text="Address: ", required=False)
    # # desired_weight = forms.IntegerField(help_text="Desired Weight: ")
    # picture = forms.ImageField(help_text="Upload image: ", required=False)
    # start_weight = forms.IntegerField(help_text="Start Weight: ")
    # views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    # likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    # slug = forms.CharField(widget=forms.HiddenInput(), required=False)
    # comments = forms.CharField(max_length=500, help_text="Comments: ", required=False)

    # An inline class to provide additional information on the form.
    class Meta:
        # Provide an association between the ModelForm and a model
        model = Client

        # fields = ('name','surname','phone')
        # fields = ('name','surname','phone', 'picture')

# class UserForm(forms.ModelForm):
#     password = forms.CharField(widget=forms.PasswordInput())
#
#     class Meta:
#         model = auth.user
#         fields = ('username', 'email', 'password')
#
# class UserProfileForm(forms.ModelForm):
#     class Meta:
#         model = UserProfile
#         fields = ('nickname',)
# #        fields = ('website', 'picture')
#


class TForm(forms.Form):
    class Meta:
       pass

       # class ImageUploadForm(forms.Form):
       #     """Image upload form."""
       #     image = forms.ImageField()

# class changeForm(forms.Form):
#     def save(self, commit=True):
#         user = super(changeForm, self).save(commit=False)
#         if user.avatar:  # If the form includes an avatar
#             user.set_avatar()  # Use this bool to check in templates
#         if commit:
#             user.save()
#         return user

job_packet/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import render, render_to_response, HttpResponse
from django.shortcuts import get_list_or_404, get_object_or_404
# Create your views here.
from django.shortcuts import render
from .models import Packet, Job
import time
from django.utils import timezone
from jalali_date import datetime2jalali, date2jalali
from job_packet.forms import TForm,ClientForm
from job_packet.models import Client
from job_packet.func import create_time,diff


def handler404(request):
    return render(request, '404.html', locals())


def handler500(request):
    return render(request, '500.html', locals())


@login_required
def show_packets(request):
    user = get_object_or_404(User, pk=request.user.pk)
    client = get_object_or_404(Client, email=user.username)
    print("url avali")
    if request.method == 'POST' and request.POST.get("form_type") == 'formOne':
        obj = Packet.objects.create(pub_date=timezone.now(), author=request.user)

    packets = Packet.objects.filter(author=request.user).order_by('pub_date')
    if len(packets)==0:
        packets=None
    return render(request, 'job_packet/packets.html', {'packets': packets , 'user':client})


@login_required
def packet_detail(request, pk):
    form = TForm(request.POST)
    packet = get_object_or_404(Packet,author=request.user, pk=pk)

    if request.method == 'POST' and request.POST.get("form_type") == 'formOne':
        obj = Packet.objects.create(pub_date=timezone.now(), author=request.user,)


        return show_packets(request)
    elif request.method == 'POST' and request.POST.get("form_type") == 'formThree':
        objs = Job.objects.filter(packet=packet)
        for i in objs:
            if i.finish_date == None:
                print( timezone.now())
                i.finish_date = timezone.now().strftime('%H:%M')

                i.lenght_date= diff(i.finish_date, i.start_date)
                i.save()

    elif request.method == 'POST':

        objs=Job.objects.filter(packet=packet)
        for i in objs:
            if i.finish_date==None:
                i.finish_date=create_time(str(timezone.now()))
                i.lenght_date= diff(i.finish_date, i.start_date)
                i.save()


        obj = Job.objects.create(heading=form.data['form_type'],start_date=timezone.now().strftime('%H:%M'),  packet=packet)


    try:
        jobsOfPacket = get_list_or_404(Job, packet=packet)
    except:
        jobsOfPacket=None

    packets = Packet.objects.filter(author=request.user).order_by('pub_date')
    user = get_object_or_404(User, pk=request.user.pk)
    client = get_object_or_404(Client, email=user.username)
    return render(request, 'job_packet/full_job_packet.html', {'packets': packets, 'jobsOfPacket': jobsOfPacket ,'user':client })


@login_required
def profile(request):
    user = get_object_or_404(User, pk=request.user.pk)
    client=get_object_or_404(Client, email=user.username)
    form=ClientForm()
    return render(request, 'profile.html', {'form': form, 'client':user , 'user':client})


@login_required
def edit_profile(request):

    user = get_object_or_404(User, pk=request.user.pk)
    client=get_object_or_404(Client, email=user.username)
    temp=client

    if request.method == 'POST':
        form = ClientForm(request.POST)

        if form.is_valid():
            # client = form.save(commit=False)


            print("hi4")
            # print(form.data['username'])
            # print(form.data['password'])
            if  (form.data['username']!= user.username and form.data['password']!= user.password):
                logout(user)
                get_object_or_404(User, username=user.username, password=user.password).delete()
                user = User.objects.create(username=form.data['username'], password=form.data['password'])
                user.save()
                login(request, user)
                client = Client.objects.create( )


            if (form.data['username'] == user.username and form.data['password'] != user.password):
                user.password=form.data['password']
                user.save()

            client.name = form.data['name']
            client.surname = form.data['surname']
            client.email = form.data['username']
            client.phone = form.data['phonenumber']
            try:
                client.picture = request.FILES['picture']
            except:
                client.picture = temp.picture



            client.save()
            return HttpResponseRedirect('/')
    form = ClientForm()
    return render(request, 'client.html', {'form2': form, 'user':client , 'client':user })


def login_user(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        try:
            user =User.objects.get(username=username, password=password)
            print(user)
            if (user != None):
                login(request,user)
                return HttpResponseRedirect('/')
            else:
                print("inja")
                render_to_response("login.html",
                           {'invalid_login': True})

        except:
            print("excepttttttt")
            return render_to_response( 'login.html', {'next': True})

    return render(request, 'login.html',{'next':False})


def add_client(request):
    user=None

    if request.method == 'POST':
        form = ClientForm(request.POST)

        if form.is_valid():
            client = Client.objects.create(name=form.data['name'], surname=form.data['surname'], email=form.data['username'],phone=form.data['phonenumber'] )
            try:
                print("\n\ninja")
                client.picture = request.FILES['picture']
                print(request.FILES['picture'])
                client.save()
                # print("inja3")
            except:
                print("except")
            print(form.data['username'])
            print(form.data['password'])
            user=User.objects.create(username=form.data['username'], password=form.data['password'])
            user.save()
            login(request, user)

            return HttpResponseRedirect('/profile/')

    form = ClientForm()
    return render(request, 'client.html', {'form2': form,'client':user})

templates/job_packet/add_client.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Add a Client{% endblock %}

{% block body_block %}

<h1>Add a Client</h1>

<form id="ClientForm" method="post" action="/address_book/add_client/" enctype="multipart/form-data">

    {% csrf_token %}
    {% for hidden in form.hidden_fields %}
        {{ hidden }}
    {% endfor %}

    {% for field in form.visible_fields %}
        {{ field.errors }}
        {{ field.help_text }}
        {{ field }}
        <br />
        <br />
    {% endfor %}

    <input type="submit" name="submit" value="Create Client" />
</form>
{% endblock %}

templates/job_packet/full_job_packet.html
{% include "job_packet/../base.html" %}
{% load static %}
{% load jalali_tags %}


{% block content %}

 <div class="uk-grid-collapse uk-child-width-expand@s uk-text-center" uk-grid >
    <div>


      <form id="formTwo" method="post" novalidate  class="uk-overflow-auto form_packet">
      {% csrf_token %}
        <div >
            <input name="form_type"  id="job_input" class="input"   style="width: 100%"  placeholder="کار جدید را وارد کنید..." >
            <input type="submit" style="position: absolute; left: -9999px"/>
        </div>
<hr>
    <table class="uk-table uk-table-hover uk-table-small uk-table-divider">

    <thead >
        <tr >
            <th><h4 class="h4">مدت زمان</h4></th>
            <th><h4 class="h4">پایان</h4></th>
            <th><h4 class="h4">شروع</h4></th>
             <th ><h4 class="h4">عنوان کار</h4></th>
        </tr>
    </thead>
    <tbody>



        {% if jobsOfPacket != None %}
            {% for job in jobsOfPacket %}
                <tr>
                {% if job.finish_date != None %}
                <td><p style="direction:rtl">{{ job.diff}}</p></td>
                <td><p style="direction:rtl">{{ job.finish_date | time:"g:i"}}</p></td>
                {% endif %}
                {% if job.finish_date ==  None %}
                <td>.....................</td>
                    <form id="formThree" method="post" novalidate >
                    {% csrf_token %}
                        <td><button class="button_finish" type="submit" value="formThree" name="form_type"> اتمام </button></td></form>
                {% endif %}
                <td ><p style="direction:rtl">

                   <time>{{ job.start_date | time:"g:i"}} </time>
                <td><p style="direction:rtl">{{ job.heading }}</p></td>
<tr>
            {% endfor %}

        {% endif %}
         {% if jobsOfPacket == None %}

         <tr>

           <td>.....................</td>
                    <td>.....................</td>
                <td>.....................</td>
                    <td>.....................</td>
             </tr>

        {% endif %}





    </tbody>
</table>







        </form>
    </div>
    <div>






                   <form id="formOne"  method="post" novalidate  class="form_packets uk-overflow-auto">

                   {%  csrf_token %}
                          <button id="yellow_button" class="button" type="submit" value="formOne" name="form_type" >ایجاد بسته کاری جدید</button>
{#                   {% if packets == None %}#}
<table class="uk-table uk-table-hover uk-table-small uk-table-divider" style="text-align: center">
                    <thead >
        <tr >
{#                               <hr style="color: white">#}

            <th><h4 class="h4_1" id="job_packet_header">  بسته های کاری</h4></th>

        </tr>
    </thead>
    <tbody>

     {% for packet in packets %}
          <tr >
            <td> <a class="p uk-button uk-button-default" href="{% url 'packet_detail' pk=packet.pk %}">{{ packet.pub_date|to_jalali:'%y/%m/%d _ %H:%M:%S' }} </a></td>
   </tr>
        {% endfor %}





{#                <tr>#}
{#                #}
{#                <td><p style="direction:rtl">{{ job.lenght_date}}</p></td>#}
{#                <td><p style="direction:rtl">{{ job.finish_date }}</p></td>#}
{#                {% endif %}#}
{#                {% if job.finish_date == "****" %}#}
{#                <td>.....................</td>#}
{#                    <form id="formThree" method="post" novalidate >#}
{#                    {% csrf_token %}#}
{#                        <td><button class="button_finish" type="submit" value="formThree" name="form_type"> اتمام </button></td></form>#}
{#                {% endif %}#}
{#                <td ><p style="direction:rtl">#}
{##}
{#                   <time datetime="%H:%M">{{ job.start_date }} </time>#}
{#                <td><p style="direction:rtl">{{ job.heading }}</p></td>#}
{#<tr>#}
{#            {% endfor %}#}
{##}
{#        {% endif %}#}
{#         {% if jobsOfPacket == None %}#}
{##}
{#         <tr>#}
{##}
{#           <td>.....................</td>#}
{#                    <td>.....................</td>#}
{#                <td>.....................</td>#}
{#                    <td>.....................</td>#}
{#             </tr>#}
{##}
{#        {% endif %}#}
{##}
{##}



    </tbody>
{#                    <h4 class="h4"> بسته های کاری</h4>#}
{#                   {% endif %}#}
{#    <div>#}
{##}
{#        {% for packet in packets %}#}
{#             <p > <a class="p uk-button uk-button-default" href="{% url 'packet_detail' pk=packet.pk %}">{{ packet.pub_date|to_jalali:'%y/%m/%d _ %H:%M:%S' }}</a></p>#}
{##}
{#        {% endfor %}#}
{##}
{#    </div>#}



</table>

</form>


    </div>
</div>






{% endblock %}

templates/job_packet/job_packet.html
<!DOCTYPE html>

<html lang="en">

<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

<style>
body {font-family: B Nazanin;}
form {border: 3px solid #f1f1f1; padding: 20px; position: absolute; right: 400px; left: 400px;}

input[type=text], input[type=password] {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    box-sizing: border-box;
}

button {
    background-color: #4CAF50;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    cursor: pointer;
    width: 100%;
    font-family: B Nazanin
}

button:hover {
    opacity: 0.8;
}

.cancelbtn {
    width: auto;
    padding: 10px 18px;
    background-color: #f44336;
}

.imgcontainer {
    text-align: center;
    margin: 24px 0 12px 0;
}

img.avatar {
    width: 60%;
    border-radius: 50%;
}

.container {
{#    float: right;#}
{#    position: relative;#}
    padding-right: 16px;
{#    margin-right: 100px;#}
{#    margin-left: 100px;#}
}

.thumbnail {
    position:relative;
    overflow:hidden;
}

.caption {
    position:absolute;
    top:0;
    right:0;
    background:rgba(66, 139, 202, 0.75);
    width:100%;
    height:100%;
    padding:2%;
    display: none;
    text-align:center;
    color:#fff !important;
    z-index:2;
}

span.psw {
    float: right;
    padding-top: 16px;
}

/* Change styles for span and cancel button on extra small screens */
@media screen and (max-width: 300px) {
    span.psw {
       display: block;
       float: none;
    }
    .cancelbtn {
       width: 100%;
    }
}
</style>
</head>

<body>
  <div class="container" style="direction: rtl;font-family: B Nazanin">

    <div id="content-container" class="container p-none"  >
        <div class="lgn-container col-lg-2" >

            <h2 align="center">فرم اطلاعات کاربری</h2>
            <form method="POST" enctype="multipart/form-data" validate>
                {% csrf_token %}
 <label for="id_username" style="direction: rtl"  >حساب کاربری</label>
                        <input required  style="direction: ltr" id="id_username"  name="username"  minlength="10"
                                   type="text" class="form-control" value="{{ user.username }}"  oninvalid="this.setCustomValidity('لطفا حساب کاربری بالای 10 کاراکتر را وارد کنید.')"  oninput="setCustomValidity('')">


                       <label style="direction: rtl" for="id_password">رمز عبور</label>
                        <input required style="direction: ltr" id="id_password" name="password"  minlength="10"
                                   type="password" class="form-control" for="pass" value="{{ user.password }}"  oninvalid="this.setCustomValidity('لطفا رمز عبوربالای 10 کاراکتر را وارد کنید.')"  oninput="setCustomValidity('')">

                <label for="id_name" style="direction: rtl"  >اسم</label>
                        <input required style="direction: rtl" id="id_name" name="name" minlength="3"
                                   type="text" class="form-control" value="{{ client.name }}"   oninvalid="this.setCustomValidity('لطفا نام را وارد کنید.')"  oninput="setCustomValidity('')">
                <label for="id_surname" style="direction: rtl" >فامیلی</label>
                        <input  style="direction: rtl" id="id_surname" name="surname" minlength="3"
                                   type="text" class="form-control" value="{{ client.surname }}"  oninvalid="this.setCustomValidity('لطفا فامیلی را وارد کنید.')"  oninput="setCustomValidity('')">
                   <label for="id_phonenumber" style="direction: rtl" >شماره همراه</label>
                        <input  style="direction: ltr" id="id_phonenumber" name="phonenumber" maxlength="11"  minlength="11"
                                   type="text" class="form-control" value="{{ client.phone }}"  oninvalid="this.setCustomValidity('لطفا شماره همراه را وارد کنید.')"  oninput="setCustomValidity('')">

                 <label for="id_picture" style="direction: rtl; float: right" >عکس</label>
{#                        <img id="theText" src="/{{ client.picture }}" width="100px" height="100px">#}
{##}

{#                 <label for="id_picture" style="direction: rtl" >عکس</label>#}
{#                        <input id="theText2"  style="direction: ltr" id="id_picture" name="picture"#}
{#                                   type="file" class="form-control" value="{{ client.picture }}" onchange="updateImage" >#}

<img id="img" alt="avatar" style="float: left" src="/{{ client.picture }}" width="150px" height="150px"/>


                <input type="file" style="float: left" name="picture" value="{{ client.picture }}"  id="picture" class="required borrowerImageFile" data-errormsg="PhotoUploadErrorMsg">

{#                {{ form2.as_p }}#}

            <button type="submit">ثبت</button>
            </form>


  </div>

{#  <div class="container" style="background-color:#f1f1f1">#}
{#    <button type="button" class="cancelbtn">Cancel</button>#}
{#    <span class="psw">Forgot <a href="#">password?</a></span>#}
{#  </div>#}
</form>


        </div>
    </div>

</div>


<script>

    $('.thumbnail').hover(
        function(){
            $(this).find('.caption').slideDown(250); //.fadeIn(250)
        },
        function(){
            $(this).find('.caption').slideUp(250); //.fadeOut(205)
        }
    );




function updateImage()
{
     alert("hello1") ;
    var image = document.getElementById("theText2");
    alert("hello") ;
    if(image.complete) {
        var new_image = new Image();
        //set up the new image
        new_image.id = "theText";
        new_image.src = image.src;
        // insert new image and remove old
        image.parentNode.insertBefore(new_image,image);
        image.parentNode.removeChild(image);
    }

    setTimeout(updateImage, 1000);

}
    function changeImage() {

        var s =(document.getElementById("input-file").value);
{#        alert(s);#}
{#        var filename = s.replace('C:\\fakepath\\', '')#}
{#        var t=s.split("\")#}




    document.getElementById("newavatar").src = ("/static/images/profile_pics/")+ s;
}

function readURL(input) {
  if (input.files && input.files[0]) {
    var reader = new FileReader();
    reader.onload = function(e) {
      $('#img').attr('src', e.target.result);
    }

    reader.readAsDataURL(input.files[0]);
  }
}

$("#picture").change(function() {
  readURL(this);
});

</script>
</body>
</html>

templates/job_packet/packets.html
{% include "job_packet/../base.html" %}
{% load static %}
{% load jalali_tags %}


{% block content %}

 <div class="uk-grid-collapse uk-child-width-expand@s uk-text-center" uk-grid >

    <div>






                   <form id="formOne"  method="post" novalidate  class="form_packets_2 uk-overflow-auto">

                   {%  csrf_token %}
                          <button id="yellow_button" class="button_2" type="submit" value="formOne" name="form_type" >ایجاد بسته کاری جدید</button>
{#                   {% if packets == None %}#}
<table class="uk-table uk-table-hover uk-table-small uk-table-divider" style="text-align: center">
  {% if packets != None %}

                    <thead >

        <tr >
{#                               <hr style="color: white">#}

            <th><h4 class="h4_1" id="job_packet_header">  بسته های کاری</h4></th>


        </tr>
    </thead>
  {% endif %}

    <tbody>

     {% for packet in packets %}
          <tr >
            <td> <a class="p_2 uk-button uk-button-default" href="{% url 'packet_detail' pk=packet.pk %}">{{ packet.pub_date|to_jalali:'%y/%m/%d _ %H:%M:%S' }} </a></td>
   </tr>
        {% endfor %}





{#                <tr>#}
{#                #}
{#                <td><p style="direction:rtl">{{ job.lenght_date}}</p></td>#}
{#                <td><p style="direction:rtl">{{ job.finish_date }}</p></td>#}
{#                {% endif %}#}
{#                {% if job.finish_date == "****" %}#}
{#                <td>.....................</td>#}
{#                    <form id="formThree" method="post" novalidate >#}
{#                    {% csrf_token %}#}
{#                        <td><button class="button_finish" type="submit" value="formThree" name="form_type"> اتمام </button></td></form>#}
{#                {% endif %}#}
{#                <td ><p style="direction:rtl">#}
{##}
{#                   <time datetime="%H:%M">{{ job.start_date }} </time>#}
{#                <td><p style="direction:rtl">{{ job.heading }}</p></td>#}
{#<tr>#}
{#            {% endfor %}#}
{##}
{#        {% endif %}#}
{#         {% if jobsOfPacket == None %}#}
{##}
{#         <tr>#}
{##}
{#           <td>.....................</td>#}
{#                    <td>.....................</td>#}
{#                <td>.....................</td>#}
{#                    <td>.....................</td>#}
{#             </tr>#}
{##}
{#        {% endif %}#}
{##}
{##}



    </tbody>
{#                    <h4 class="h4"> بسته های کاری</h4>#}
{#                   {% endif %}#}
{#    <div>#}
{##}
{#        {% for packet in packets %}#}
{#             <p > <a class="p uk-button uk-button-default" href="{% url 'packet_detail' pk=packet.pk %}">{{ packet.pub_date|to_jalali:'%y/%m/%d _ %H:%M:%S' }}</a></p>#}
{##}
{#        {% endfor %}#}
{##}
{#    </div>#}



</table>

</form>


    </div>
</div>






{% endblock %}